trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn --cwd examples run auto-install
    yarn run build
  displayName: 'run build'

- script: |
    yarn run clean
  displayName: 'run clean'
